/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AListvariablesListvariables extends PListvariables
{
    private TComma _comma_;
    private PValue _value_;
    private PListvariables _listvariables_;

    public AListvariablesListvariables()
    {
        // Constructor
    }

    public AListvariablesListvariables(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PValue _value_,
        @SuppressWarnings("hiding") PListvariables _listvariables_)
    {
        // Constructor
        setComma(_comma_);

        setValue(_value_);

        setListvariables(_listvariables_);

    }

    @Override
    public Object clone()
    {
        return new AListvariablesListvariables(
            cloneNode(this._comma_),
            cloneNode(this._value_),
            cloneNode(this._listvariables_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListvariablesListvariables(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    public PListvariables getListvariables()
    {
        return this._listvariables_;
    }

    public void setListvariables(PListvariables node)
    {
        if(this._listvariables_ != null)
        {
            this._listvariables_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listvariables_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._value_)
            + toString(this._listvariables_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        if(this._listvariables_ == child)
        {
            this._listvariables_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        if(this._listvariables_ == oldChild)
        {
            setListvariables((PListvariables) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
