/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AOpcompare4Opcompare extends POpcompare
{
    private POpcompare _opcompare_;
    private TGreaterEqual _greaterEqual_;
    private PValue _value_;

    public AOpcompare4Opcompare()
    {
        // Constructor
    }

    public AOpcompare4Opcompare(
        @SuppressWarnings("hiding") POpcompare _opcompare_,
        @SuppressWarnings("hiding") TGreaterEqual _greaterEqual_,
        @SuppressWarnings("hiding") PValue _value_)
    {
        // Constructor
        setOpcompare(_opcompare_);

        setGreaterEqual(_greaterEqual_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AOpcompare4Opcompare(
            cloneNode(this._opcompare_),
            cloneNode(this._greaterEqual_),
            cloneNode(this._value_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpcompare4Opcompare(this);
    }

    public POpcompare getOpcompare()
    {
        return this._opcompare_;
    }

    public void setOpcompare(POpcompare node)
    {
        if(this._opcompare_ != null)
        {
            this._opcompare_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcompare_ = node;
    }

    public TGreaterEqual getGreaterEqual()
    {
        return this._greaterEqual_;
    }

    public void setGreaterEqual(TGreaterEqual node)
    {
        if(this._greaterEqual_ != null)
        {
            this._greaterEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterEqual_ = node;
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opcompare_)
            + toString(this._greaterEqual_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opcompare_ == child)
        {
            this._opcompare_ = null;
            return;
        }

        if(this._greaterEqual_ == child)
        {
            this._greaterEqual_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opcompare_ == oldChild)
        {
            setOpcompare((POpcompare) newChild);
            return;
        }

        if(this._greaterEqual_ == oldChild)
        {
            setGreaterEqual((TGreaterEqual) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
