/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ASayAction extends PAction
{
    private PActionsay _actionsay_;

    public ASayAction()
    {
        // Constructor
    }

    public ASayAction(
        @SuppressWarnings("hiding") PActionsay _actionsay_)
    {
        // Constructor
        setActionsay(_actionsay_);

    }

    @Override
    public Object clone()
    {
        return new ASayAction(
            cloneNode(this._actionsay_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASayAction(this);
    }

    public PActionsay getActionsay()
    {
        return this._actionsay_;
    }

    public void setActionsay(PActionsay node)
    {
        if(this._actionsay_ != null)
        {
            this._actionsay_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actionsay_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actionsay_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actionsay_ == child)
        {
            this._actionsay_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actionsay_ == oldChild)
        {
            setActionsay((PActionsay) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
