/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AVardeclDecl extends PDecl
{
    private PVardecl _vardecl_;

    public AVardeclDecl()
    {
        // Constructor
    }

    public AVardeclDecl(
        @SuppressWarnings("hiding") PVardecl _vardecl_)
    {
        // Constructor
        setVardecl(_vardecl_);

    }

    @Override
    public Object clone()
    {
        return new AVardeclDecl(
            cloneNode(this._vardecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVardeclDecl(this);
    }

    public PVardecl getVardecl()
    {
        return this._vardecl_;
    }

    public void setVardecl(PVardecl node)
    {
        if(this._vardecl_ != null)
        {
            this._vardecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vardecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vardecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vardecl_ == child)
        {
            this._vardecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vardecl_ == oldChild)
        {
            setVardecl((PVardecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
