/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TSay extends Token
{
    public TSay()
    {
        super.setText("say");
    }

    public TSay(int line, int pos)
    {
        super.setText("say");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSay(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSay(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSay text.");
    }
}
