/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.analysis;

import java.util.*;
import compiler.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getEventDecl() != null)
        {
            node.getEventDecl().apply(this);
        }
        {
            List<PFuncDecl> copy = new ArrayList<PFuncDecl>(node.getFuncDecl());
            Collections.reverse(copy);
            for(PFuncDecl e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getMain() != null)
        {
            node.getMain().apply(this);
        }
        {
            List<PGlobalDecls> copy = new ArrayList<PGlobalDecls>(node.getGlobalDecls());
            Collections.reverse(copy);
            for(PGlobalDecls e : copy)
            {
                e.apply(this);
            }
        }
        outAProgram(node);
    }

    public void inAVariableDeclDecl(AVariableDeclDecl node)
    {
        defaultIn(node);
    }

    public void outAVariableDeclDecl(AVariableDeclDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariableDeclDecl(AVariableDeclDecl node)
    {
        inAVariableDeclDecl(node);
        if(node.getVariableDecl() != null)
        {
            node.getVariableDecl().apply(this);
        }
        outAVariableDeclDecl(node);
    }

    public void inAControlStmtDecl(AControlStmtDecl node)
    {
        defaultIn(node);
    }

    public void outAControlStmtDecl(AControlStmtDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAControlStmtDecl(AControlStmtDecl node)
    {
        inAControlStmtDecl(node);
        if(node.getControlStmt() != null)
        {
            node.getControlStmt().apply(this);
        }
        outAControlStmtDecl(node);
    }

    public void inAAssignDecl(AAssignDecl node)
    {
        defaultIn(node);
    }

    public void outAAssignDecl(AAssignDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignDecl(AAssignDecl node)
    {
        inAAssignDecl(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAAssignDecl(node);
    }

    public void inAVarGlobalDecls(AVarGlobalDecls node)
    {
        defaultIn(node);
    }

    public void outAVarGlobalDecls(AVarGlobalDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarGlobalDecls(AVarGlobalDecls node)
    {
        inAVarGlobalDecls(node);
        if(node.getVariableDecl() != null)
        {
            node.getVariableDecl().apply(this);
        }
        outAVarGlobalDecls(node);
    }

    public void inAObjGlobalDecls(AObjGlobalDecls node)
    {
        defaultIn(node);
    }

    public void outAObjGlobalDecls(AObjGlobalDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjGlobalDecls(AObjGlobalDecls node)
    {
        inAObjGlobalDecls(node);
        if(node.getObjectDecl() != null)
        {
            node.getObjectDecl().apply(this);
        }
        outAObjGlobalDecls(node);
    }

    public void inAGridGlobalDecls(AGridGlobalDecls node)
    {
        defaultIn(node);
    }

    public void outAGridGlobalDecls(AGridGlobalDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGridGlobalDecls(AGridGlobalDecls node)
    {
        inAGridGlobalDecls(node);
        if(node.getGridDecl() != null)
        {
            node.getGridDecl().apply(this);
        }
        outAGridGlobalDecls(node);
    }

    public void inAEventDecl(AEventDecl node)
    {
        defaultIn(node);
    }

    public void outAEventDecl(AEventDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEventDecl(AEventDecl node)
    {
        inAEventDecl(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getEvent() != null)
        {
            node.getEvent().apply(this);
        }
        outAEventDecl(node);
    }

    public void inAGridDecl(AGridDecl node)
    {
        defaultIn(node);
    }

    public void outAGridDecl(AGridDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGridDecl(AGridDecl node)
    {
        inAGridDecl(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getInt2() != null)
        {
            node.getInt2().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getInt1() != null)
        {
            node.getInt1().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getGrid() != null)
        {
            node.getGrid().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getNew() != null)
        {
            node.getNew().apply(this);
        }
        outAGridDecl(node);
    }

    public void inAObjectDecl(AObjectDecl node)
    {
        defaultIn(node);
    }

    public void outAObjectDecl(AObjectDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjectDecl(AObjectDecl node)
    {
        inAObjectDecl(node);
        if(node.getObjBody() != null)
        {
            node.getObjBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getId2() != null)
        {
            node.getId2().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getFigure() != null)
        {
            node.getFigure().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getId1() != null)
        {
            node.getId1().apply(this);
        }
        if(node.getNew() != null)
        {
            node.getNew().apply(this);
        }
        outAObjectDecl(node);
    }

    public void inAFuncDecl(AFuncDecl node)
    {
        defaultIn(node);
    }

    public void outAFuncDecl(AFuncDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDecl(AFuncDecl node)
    {
        inAFuncDecl(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getParams() != null)
        {
            node.getParams().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getNew() != null)
        {
            node.getNew().apply(this);
        }
        outAFuncDecl(node);
    }

    public void inAVariableDecl(AVariableDecl node)
    {
        defaultIn(node);
    }

    public void outAVariableDecl(AVariableDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariableDecl(AVariableDecl node)
    {
        inAVariableDecl(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getVariables() != null)
        {
            node.getVariables().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getNew() != null)
        {
            node.getNew().apply(this);
        }
        outAVariableDecl(node);
    }

    public void inAExprVariables(AExprVariables node)
    {
        defaultIn(node);
    }

    public void outAExprVariables(AExprVariables node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprVariables(AExprVariables node)
    {
        inAExprVariables(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAExprVariables(node);
    }

    public void inAListVariables(AListVariables node)
    {
        defaultIn(node);
    }

    public void outAListVariables(AListVariables node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListVariables(AListVariables node)
    {
        inAListVariables(node);
        if(node.getBrackR() != null)
        {
            node.getBrackR().apply(this);
        }
        {
            List<PListVarTail> copy = new ArrayList<PListVarTail>(node.getListVarTail());
            Collections.reverse(copy);
            for(PListVarTail e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        if(node.getBrackL() != null)
        {
            node.getBrackL().apply(this);
        }
        outAListVariables(node);
    }

    public void inAListVarTail(AListVarTail node)
    {
        defaultIn(node);
    }

    public void outAListVarTail(AListVarTail node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListVarTail(AListVarTail node)
    {
        inAListVarTail(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outAListVarTail(node);
    }

    public void inACallParams(ACallParams node)
    {
        defaultIn(node);
    }

    public void outACallParams(ACallParams node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallParams(ACallParams node)
    {
        inACallParams(node);
        {
            List<PCallParamsTail> copy = new ArrayList<PCallParamsTail>(node.getCallParamsTail());
            Collections.reverse(copy);
            for(PCallParamsTail e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outACallParams(node);
    }

    public void inACallParamsTail(ACallParamsTail node)
    {
        defaultIn(node);
    }

    public void outACallParamsTail(ACallParamsTail node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallParamsTail(ACallParamsTail node)
    {
        inACallParamsTail(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outACallParamsTail(node);
    }

    public void inAReturnValue(AReturnValue node)
    {
        defaultIn(node);
    }

    public void outAReturnValue(AReturnValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReturnValue(AReturnValue node)
    {
        inAReturnValue(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getReturn() != null)
        {
            node.getReturn().apply(this);
        }
        outAReturnValue(node);
    }

    public void inAParams(AParams node)
    {
        defaultIn(node);
    }

    public void outAParams(AParams node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParams(AParams node)
    {
        inAParams(node);
        {
            List<PParamsTail> copy = new ArrayList<PParamsTail>(node.getParamsTail());
            Collections.reverse(copy);
            for(PParamsTail e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAParams(node);
    }

    public void inAParamsTail(AParamsTail node)
    {
        defaultIn(node);
    }

    public void outAParamsTail(AParamsTail node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamsTail(AParamsTail node)
    {
        inAParamsTail(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outAParamsTail(node);
    }

    public void inAWhileControlStmt(AWhileControlStmt node)
    {
        defaultIn(node);
    }

    public void outAWhileControlStmt(AWhileControlStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileControlStmt(AWhileControlStmt node)
    {
        inAWhileControlStmt(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getRepeat() != null)
        {
            node.getRepeat().apply(this);
        }
        outAWhileControlStmt(node);
    }

    public void inARepeatControlStmt(ARepeatControlStmt node)
    {
        defaultIn(node);
    }

    public void outARepeatControlStmt(ARepeatControlStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARepeatControlStmt(ARepeatControlStmt node)
    {
        inARepeatControlStmt(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getRepeat() != null)
        {
            node.getRepeat().apply(this);
        }
        outARepeatControlStmt(node);
    }

    public void inAForeachControlStmt(AForeachControlStmt node)
    {
        defaultIn(node);
    }

    public void outAForeachControlStmt(AForeachControlStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForeachControlStmt(AForeachControlStmt node)
    {
        inAForeachControlStmt(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getList() != null)
        {
            node.getList().apply(this);
        }
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getForeach() != null)
        {
            node.getForeach().apply(this);
        }
        if(node.getRepeat() != null)
        {
            node.getRepeat().apply(this);
        }
        outAForeachControlStmt(node);
    }

    public void inAIfStmtControlStmt(AIfStmtControlStmt node)
    {
        defaultIn(node);
    }

    public void outAIfStmtControlStmt(AIfStmtControlStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfStmtControlStmt(AIfStmtControlStmt node)
    {
        inAIfStmtControlStmt(node);
        if(node.getElseStmt() != null)
        {
            node.getElseStmt().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAIfStmtControlStmt(node);
    }

    public void inAElseStmtElseStmt(AElseStmtElseStmt node)
    {
        defaultIn(node);
    }

    public void outAElseStmtElseStmt(AElseStmtElseStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseStmtElseStmt(AElseStmtElseStmt node)
    {
        inAElseStmtElseStmt(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseStmtElseStmt(node);
    }

    public void inAElseifStmtElseStmt(AElseifStmtElseStmt node)
    {
        defaultIn(node);
    }

    public void outAElseifStmtElseStmt(AElseifStmtElseStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseifStmtElseStmt(AElseifStmtElseStmt node)
    {
        inAElseifStmtElseStmt(node);
        if(node.getElseStmt() != null)
        {
            node.getElseStmt().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseifStmtElseStmt(node);
    }

    public void inABody(ABody node)
    {
        defaultIn(node);
    }

    public void outABody(ABody node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABody(ABody node)
    {
        inABody(node);
        if(node.getCurlyR() != null)
        {
            node.getCurlyR().apply(this);
        }
        if(node.getReturnValue() != null)
        {
            node.getReturnValue().apply(this);
        }
        {
            List<PDecl> copy = new ArrayList<PDecl>(node.getDecl());
            Collections.reverse(copy);
            for(PDecl e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCurlyL() != null)
        {
            node.getCurlyL().apply(this);
        }
        outABody(node);
    }

    public void inAObjBody(AObjBody node)
    {
        defaultIn(node);
    }

    public void outAObjBody(AObjBody node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjBody(AObjBody node)
    {
        inAObjBody(node);
        if(node.getCurlyR() != null)
        {
            node.getCurlyR().apply(this);
        }
        {
            List<PObjDecls> copy = new ArrayList<PObjDecls>(node.getObjDecls());
            Collections.reverse(copy);
            for(PObjDecls e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCurlyL() != null)
        {
            node.getCurlyL().apply(this);
        }
        outAObjBody(node);
    }

    public void inADeclObjDecls(ADeclObjDecls node)
    {
        defaultIn(node);
    }

    public void outADeclObjDecls(ADeclObjDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclObjDecls(ADeclObjDecls node)
    {
        inADeclObjDecls(node);
        if(node.getDecl() != null)
        {
            node.getDecl().apply(this);
        }
        outADeclObjDecls(node);
    }

    public void inAObjDeclsObjDecls(AObjDeclsObjDecls node)
    {
        defaultIn(node);
    }

    public void outAObjDeclsObjDecls(AObjDeclsObjDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDeclsObjDecls(AObjDeclsObjDecls node)
    {
        inAObjDeclsObjDecls(node);
        if(node.getFuncDecl() != null)
        {
            node.getFuncDecl().apply(this);
        }
        outAObjDeclsObjDecls(node);
    }

    public void inAAssignExpr(AAssignExpr node)
    {
        defaultIn(node);
    }

    public void outAAssignExpr(AAssignExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignExpr(AAssignExpr node)
    {
        inAAssignExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAAssignExpr(node);
    }

    public void inAIncrementExpr(AIncrementExpr node)
    {
        defaultIn(node);
    }

    public void outAIncrementExpr(AIncrementExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIncrementExpr(AIncrementExpr node)
    {
        inAIncrementExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getIncrement() != null)
        {
            node.getIncrement().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAIncrementExpr(node);
    }

    public void inADecrementExpr(ADecrementExpr node)
    {
        defaultIn(node);
    }

    public void outADecrementExpr(ADecrementExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecrementExpr(ADecrementExpr node)
    {
        inADecrementExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getDecrement() != null)
        {
            node.getDecrement().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outADecrementExpr(node);
    }

    public void inABooleanExpr(ABooleanExpr node)
    {
        defaultIn(node);
    }

    public void outABooleanExpr(ABooleanExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanExpr(ABooleanExpr node)
    {
        inABooleanExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getBoolOperator() != null)
        {
            node.getBoolOperator().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outABooleanExpr(node);
    }

    public void inANumericExpr(ANumericExpr node)
    {
        defaultIn(node);
    }

    public void outANumericExpr(ANumericExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumericExpr(ANumericExpr node)
    {
        inANumericExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getOperator() != null)
        {
            node.getOperator().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outANumericExpr(node);
    }

    public void inAMinusvalueExpr(AMinusvalueExpr node)
    {
        defaultIn(node);
    }

    public void outAMinusvalueExpr(AMinusvalueExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusvalueExpr(AMinusvalueExpr node)
    {
        inAMinusvalueExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outAMinusvalueExpr(node);
    }

    public void inAValueExpr(AValueExpr node)
    {
        defaultIn(node);
    }

    public void outAValueExpr(AValueExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValueExpr(AValueExpr node)
    {
        inAValueExpr(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAValueExpr(node);
    }

    public void inAParamaExpr(AParamaExpr node)
    {
        defaultIn(node);
    }

    public void outAParamaExpr(AParamaExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamaExpr(AParamaExpr node)
    {
        inAParamaExpr(node);
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        outAParamaExpr(node);
    }

    public void inAParamaBoolExpr(AParamaBoolExpr node)
    {
        defaultIn(node);
    }

    public void outAParamaBoolExpr(AParamaBoolExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamaBoolExpr(AParamaBoolExpr node)
    {
        inAParamaBoolExpr(node);
        if(node.getForllowExpr() != null)
        {
            node.getForllowExpr().apply(this);
        }
        if(node.getBoolOperator() != null)
        {
            node.getBoolOperator().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        outAParamaBoolExpr(node);
    }

    public void inAParamaNumericExpr(AParamaNumericExpr node)
    {
        defaultIn(node);
    }

    public void outAParamaNumericExpr(AParamaNumericExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamaNumericExpr(AParamaNumericExpr node)
    {
        inAParamaNumericExpr(node);
        if(node.getForllowExpr() != null)
        {
            node.getForllowExpr().apply(this);
        }
        if(node.getOperator() != null)
        {
            node.getOperator().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        outAParamaNumericExpr(node);
    }

    public void inAValueValue(AValueValue node)
    {
        defaultIn(node);
    }

    public void outAValueValue(AValueValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValueValue(AValueValue node)
    {
        inAValueValue(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAValueValue(node);
    }

    public void inAValueMemberValue(AValueMemberValue node)
    {
        defaultIn(node);
    }

    public void outAValueMemberValue(AValueMemberValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValueMemberValue(AValueMemberValue node)
    {
        inAValueMemberValue(node);
        if(node.getMember() != null)
        {
            node.getMember().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAValueMemberValue(node);
    }

    public void inAFuncCallValue(AFuncCallValue node)
    {
        defaultIn(node);
    }

    public void outAFuncCallValue(AFuncCallValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallValue(AFuncCallValue node)
    {
        inAFuncCallValue(node);
        if(node.getFuncCall() != null)
        {
            node.getFuncCall().apply(this);
        }
        outAFuncCallValue(node);
    }

    public void inALiteralValue(ALiteralValue node)
    {
        defaultIn(node);
    }

    public void outALiteralValue(ALiteralValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALiteralValue(ALiteralValue node)
    {
        inALiteralValue(node);
        if(node.getLiteral() != null)
        {
            node.getLiteral().apply(this);
        }
        outALiteralValue(node);
    }

    public void inAFuncCall(AFuncCall node)
    {
        defaultIn(node);
    }

    public void outAFuncCall(AFuncCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCall(AFuncCall node)
    {
        inAFuncCall(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getCallParams() != null)
        {
            node.getCallParams().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFuncCall(node);
    }

    public void inADotMember(ADotMember node)
    {
        defaultIn(node);
    }

    public void outADotMember(ADotMember node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADotMember(ADotMember node)
    {
        inADotMember(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getDot() != null)
        {
            node.getDot().apply(this);
        }
        outADotMember(node);
    }

    public void inAMethodCallMember(AMethodCallMember node)
    {
        defaultIn(node);
    }

    public void outAMethodCallMember(AMethodCallMember node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodCallMember(AMethodCallMember node)
    {
        inAMethodCallMember(node);
        if(node.getParR() != null)
        {
            node.getParR().apply(this);
        }
        if(node.getCallParams() != null)
        {
            node.getCallParams().apply(this);
        }
        if(node.getParL() != null)
        {
            node.getParL().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getDot() != null)
        {
            node.getDot().apply(this);
        }
        outAMethodCallMember(node);
    }

    public void inAMinusOperator(AMinusOperator node)
    {
        defaultIn(node);
    }

    public void outAMinusOperator(AMinusOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusOperator(AMinusOperator node)
    {
        inAMinusOperator(node);
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outAMinusOperator(node);
    }

    public void inAPlusOperator(APlusOperator node)
    {
        defaultIn(node);
    }

    public void outAPlusOperator(APlusOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusOperator(APlusOperator node)
    {
        inAPlusOperator(node);
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        outAPlusOperator(node);
    }

    public void inAMultOperator(AMultOperator node)
    {
        defaultIn(node);
    }

    public void outAMultOperator(AMultOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultOperator(AMultOperator node)
    {
        inAMultOperator(node);
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        outAMultOperator(node);
    }

    public void inADivOperator(ADivOperator node)
    {
        defaultIn(node);
    }

    public void outADivOperator(ADivOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivOperator(ADivOperator node)
    {
        inADivOperator(node);
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        outADivOperator(node);
    }

    public void inAEqualBoolOperator(AEqualBoolOperator node)
    {
        defaultIn(node);
    }

    public void outAEqualBoolOperator(AEqualBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqualBoolOperator(AEqualBoolOperator node)
    {
        inAEqualBoolOperator(node);
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        outAEqualBoolOperator(node);
    }

    public void inALessEqualBoolOperator(ALessEqualBoolOperator node)
    {
        defaultIn(node);
    }

    public void outALessEqualBoolOperator(ALessEqualBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessEqualBoolOperator(ALessEqualBoolOperator node)
    {
        inALessEqualBoolOperator(node);
        if(node.getLessEqual() != null)
        {
            node.getLessEqual().apply(this);
        }
        outALessEqualBoolOperator(node);
    }

    public void inAGreaterEqualBoolOperator(AGreaterEqualBoolOperator node)
    {
        defaultIn(node);
    }

    public void outAGreaterEqualBoolOperator(AGreaterEqualBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterEqualBoolOperator(AGreaterEqualBoolOperator node)
    {
        inAGreaterEqualBoolOperator(node);
        if(node.getGreaterEqual() != null)
        {
            node.getGreaterEqual().apply(this);
        }
        outAGreaterEqualBoolOperator(node);
    }

    public void inANegateBoolOperator(ANegateBoolOperator node)
    {
        defaultIn(node);
    }

    public void outANegateBoolOperator(ANegateBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegateBoolOperator(ANegateBoolOperator node)
    {
        inANegateBoolOperator(node);
        if(node.getNegate() != null)
        {
            node.getNegate().apply(this);
        }
        outANegateBoolOperator(node);
    }

    public void inAAndBoolOperator(AAndBoolOperator node)
    {
        defaultIn(node);
    }

    public void outAAndBoolOperator(AAndBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndBoolOperator(AAndBoolOperator node)
    {
        inAAndBoolOperator(node);
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        outAAndBoolOperator(node);
    }

    public void inAOrBoolOperator(AOrBoolOperator node)
    {
        defaultIn(node);
    }

    public void outAOrBoolOperator(AOrBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrBoolOperator(AOrBoolOperator node)
    {
        inAOrBoolOperator(node);
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        outAOrBoolOperator(node);
    }

    public void inALessBoolOperator(ALessBoolOperator node)
    {
        defaultIn(node);
    }

    public void outALessBoolOperator(ALessBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessBoolOperator(ALessBoolOperator node)
    {
        inALessBoolOperator(node);
        if(node.getLess() != null)
        {
            node.getLess().apply(this);
        }
        outALessBoolOperator(node);
    }

    public void inAGreaterBoolOperator(AGreaterBoolOperator node)
    {
        defaultIn(node);
    }

    public void outAGreaterBoolOperator(AGreaterBoolOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterBoolOperator(AGreaterBoolOperator node)
    {
        inAGreaterBoolOperator(node);
        if(node.getGreater() != null)
        {
            node.getGreater().apply(this);
        }
        outAGreaterBoolOperator(node);
    }

    public void inABooleanLiteral(ABooleanLiteral node)
    {
        defaultIn(node);
    }

    public void outABooleanLiteral(ABooleanLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanLiteral(ABooleanLiteral node)
    {
        inABooleanLiteral(node);
        if(node.getBooleanLiteral() != null)
        {
            node.getBooleanLiteral().apply(this);
        }
        outABooleanLiteral(node);
    }

    public void inAIntegerLiteral(AIntegerLiteral node)
    {
        defaultIn(node);
    }

    public void outAIntegerLiteral(AIntegerLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerLiteral(AIntegerLiteral node)
    {
        inAIntegerLiteral(node);
        if(node.getIntegerLiteral() != null)
        {
            node.getIntegerLiteral().apply(this);
        }
        outAIntegerLiteral(node);
    }

    public void inADoubleLiteral(ADoubleLiteral node)
    {
        defaultIn(node);
    }

    public void outADoubleLiteral(ADoubleLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoubleLiteral(ADoubleLiteral node)
    {
        inADoubleLiteral(node);
        if(node.getDoubleLiteral() != null)
        {
            node.getDoubleLiteral().apply(this);
        }
        outADoubleLiteral(node);
    }

    public void inAStringLiteral(AStringLiteral node)
    {
        defaultIn(node);
    }

    public void outAStringLiteral(AStringLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringLiteral(AStringLiteral node)
    {
        inAStringLiteral(node);
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        outAStringLiteral(node);
    }

    public void inATrueBooleanLiteral(ATrueBooleanLiteral node)
    {
        defaultIn(node);
    }

    public void outATrueBooleanLiteral(ATrueBooleanLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATrueBooleanLiteral(ATrueBooleanLiteral node)
    {
        inATrueBooleanLiteral(node);
        if(node.getTrue() != null)
        {
            node.getTrue().apply(this);
        }
        outATrueBooleanLiteral(node);
    }

    public void inAFalseBooleanLiteral(AFalseBooleanLiteral node)
    {
        defaultIn(node);
    }

    public void outAFalseBooleanLiteral(AFalseBooleanLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFalseBooleanLiteral(AFalseBooleanLiteral node)
    {
        inAFalseBooleanLiteral(node);
        if(node.getFalse() != null)
        {
            node.getFalse().apply(this);
        }
        outAFalseBooleanLiteral(node);
    }
}
