/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ALessOpcompare extends POpcompare
{
    private POpcompare _opcompare_;
    private TLess _less_;
    private PValue _value_;

    public ALessOpcompare()
    {
        // Constructor
    }

    public ALessOpcompare(
        @SuppressWarnings("hiding") POpcompare _opcompare_,
        @SuppressWarnings("hiding") TLess _less_,
        @SuppressWarnings("hiding") PValue _value_)
    {
        // Constructor
        setOpcompare(_opcompare_);

        setLess(_less_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new ALessOpcompare(
            cloneNode(this._opcompare_),
            cloneNode(this._less_),
            cloneNode(this._value_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessOpcompare(this);
    }

    public POpcompare getOpcompare()
    {
        return this._opcompare_;
    }

    public void setOpcompare(POpcompare node)
    {
        if(this._opcompare_ != null)
        {
            this._opcompare_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcompare_ = node;
    }

    public TLess getLess()
    {
        return this._less_;
    }

    public void setLess(TLess node)
    {
        if(this._less_ != null)
        {
            this._less_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._less_ = node;
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opcompare_)
            + toString(this._less_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opcompare_ == child)
        {
            this._opcompare_ = null;
            return;
        }

        if(this._less_ == child)
        {
            this._less_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opcompare_ == oldChild)
        {
            setOpcompare((POpcompare) newChild);
            return;
        }

        if(this._less_ == oldChild)
        {
            setLess((TLess) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
