/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AControlStatementsDecl extends PDecl
{
    private PControlStatments _controlStatments_;

    public AControlStatementsDecl()
    {
        // Constructor
    }

    public AControlStatementsDecl(
        @SuppressWarnings("hiding") PControlStatments _controlStatments_)
    {
        // Constructor
        setControlStatments(_controlStatments_);

    }

    @Override
    public Object clone()
    {
        return new AControlStatementsDecl(
            cloneNode(this._controlStatments_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAControlStatementsDecl(this);
    }

    public PControlStatments getControlStatments()
    {
        return this._controlStatments_;
    }

    public void setControlStatments(PControlStatments node)
    {
        if(this._controlStatments_ != null)
        {
            this._controlStatments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._controlStatments_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._controlStatments_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._controlStatments_ == child)
        {
            this._controlStatments_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._controlStatments_ == oldChild)
        {
            setControlStatments((PControlStatments) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
