/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ARightParam extends PRightParam
{
    private TComma _comma_;
    private POpadd _opadd_;

    public ARightParam()
    {
        // Constructor
    }

    public ARightParam(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") POpadd _opadd_)
    {
        // Constructor
        setComma(_comma_);

        setOpadd(_opadd_);

    }

    @Override
    public Object clone()
    {
        return new ARightParam(
            cloneNode(this._comma_),
            cloneNode(this._opadd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightParam(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public POpadd getOpadd()
    {
        return this._opadd_;
    }

    public void setOpadd(POpadd node)
    {
        if(this._opadd_ != null)
        {
            this._opadd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opadd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._opadd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._opadd_ == child)
        {
            this._opadd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._opadd_ == oldChild)
        {
            setOpadd((POpadd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
