/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterEqualBoolOperator extends PBoolOperator
{
    private TGreaterEqual _greaterEqual_;

    public AGreaterEqualBoolOperator()
    {
        // Constructor
    }

    public AGreaterEqualBoolOperator(
        @SuppressWarnings("hiding") TGreaterEqual _greaterEqual_)
    {
        // Constructor
        setGreaterEqual(_greaterEqual_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterEqualBoolOperator(
            cloneNode(this._greaterEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterEqualBoolOperator(this);
    }

    public TGreaterEqual getGreaterEqual()
    {
        return this._greaterEqual_;
    }

    public void setGreaterEqual(TGreaterEqual node)
    {
        if(this._greaterEqual_ != null)
        {
            this._greaterEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._greaterEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._greaterEqual_ == child)
        {
            this._greaterEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._greaterEqual_ == oldChild)
        {
            setGreaterEqual((TGreaterEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
