/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AOporOpassign extends POpassign
{
    private POpor _opor_;

    public AOporOpassign()
    {
        // Constructor
    }

    public AOporOpassign(
        @SuppressWarnings("hiding") POpor _opor_)
    {
        // Constructor
        setOpor(_opor_);

    }

    @Override
    public Object clone()
    {
        return new AOporOpassign(
            cloneNode(this._opor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOporOpassign(this);
    }

    public POpor getOpor()
    {
        return this._opor_;
    }

    public void setOpor(POpor node)
    {
        if(this._opor_ != null)
        {
            this._opor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opor_ == child)
        {
            this._opor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opor_ == oldChild)
        {
            setOpor((POpor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
