/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AThinkAction extends PAction
{
    private PActionthink _actionthink_;

    public AThinkAction()
    {
        // Constructor
    }

    public AThinkAction(
        @SuppressWarnings("hiding") PActionthink _actionthink_)
    {
        // Constructor
        setActionthink(_actionthink_);

    }

    @Override
    public Object clone()
    {
        return new AThinkAction(
            cloneNode(this._actionthink_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAThinkAction(this);
    }

    public PActionthink getActionthink()
    {
        return this._actionthink_;
    }

    public void setActionthink(PActionthink node)
    {
        if(this._actionthink_ != null)
        {
            this._actionthink_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actionthink_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actionthink_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actionthink_ == child)
        {
            this._actionthink_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actionthink_ == oldChild)
        {
            setActionthink((PActionthink) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
