/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TStartup extends Token
{
    public TStartup()
    {
        super.setText("startup");
    }

    public TStartup(int line, int pos)
    {
        super.setText("startup");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStartup(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStartup(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStartup text.");
    }
}
