/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AOrOpor extends POpor
{
    private POpor _opor_;
    private TOr _or_;
    private POpand _opand_;

    public AOrOpor()
    {
        // Constructor
    }

    public AOrOpor(
        @SuppressWarnings("hiding") POpor _opor_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") POpand _opand_)
    {
        // Constructor
        setOpor(_opor_);

        setOr(_or_);

        setOpand(_opand_);

    }

    @Override
    public Object clone()
    {
        return new AOrOpor(
            cloneNode(this._opor_),
            cloneNode(this._or_),
            cloneNode(this._opand_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrOpor(this);
    }

    public POpor getOpor()
    {
        return this._opor_;
    }

    public void setOpor(POpor node)
    {
        if(this._opor_ != null)
        {
            this._opor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opor_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public POpand getOpand()
    {
        return this._opand_;
    }

    public void setOpand(POpand node)
    {
        if(this._opand_ != null)
        {
            this._opand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opor_)
            + toString(this._or_)
            + toString(this._opand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opor_ == child)
        {
            this._opor_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._opand_ == child)
        {
            this._opand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opor_ == oldChild)
        {
            setOpor((POpor) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._opand_ == oldChild)
        {
            setOpand((POpand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
