/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ARndValue extends PValue
{
    private PRnd _rnd_;

    public ARndValue()
    {
        // Constructor
    }

    public ARndValue(
        @SuppressWarnings("hiding") PRnd _rnd_)
    {
        // Constructor
        setRnd(_rnd_);

    }

    @Override
    public Object clone()
    {
        return new ARndValue(
            cloneNode(this._rnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARndValue(this);
    }

    public PRnd getRnd()
    {
        return this._rnd_;
    }

    public void setRnd(PRnd node)
    {
        if(this._rnd_ != null)
        {
            this._rnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rnd_ == child)
        {
            this._rnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rnd_ == oldChild)
        {
            setRnd((PRnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
