/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ABoolExpr extends PBoolExpr
{
    private PValue _value_;
    private PBoolOperator _boolOperator_;
    private PExpr _expr_;

    public ABoolExpr()
    {
        // Constructor
    }

    public ABoolExpr(
        @SuppressWarnings("hiding") PValue _value_,
        @SuppressWarnings("hiding") PBoolOperator _boolOperator_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setValue(_value_);

        setBoolOperator(_boolOperator_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new ABoolExpr(
            cloneNode(this._value_),
            cloneNode(this._boolOperator_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolExpr(this);
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    public PBoolOperator getBoolOperator()
    {
        return this._boolOperator_;
    }

    public void setBoolOperator(PBoolOperator node)
    {
        if(this._boolOperator_ != null)
        {
            this._boolOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolOperator_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._value_)
            + toString(this._boolOperator_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        if(this._boolOperator_ == child)
        {
            this._boolOperator_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        if(this._boolOperator_ == oldChild)
        {
            setBoolOperator((PBoolOperator) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
