/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AGridGlobalDecl extends PGlobalDecl
{
    private PGridDecl _gridDecl_;

    public AGridGlobalDecl()
    {
        // Constructor
    }

    public AGridGlobalDecl(
        @SuppressWarnings("hiding") PGridDecl _gridDecl_)
    {
        // Constructor
        setGridDecl(_gridDecl_);

    }

    @Override
    public Object clone()
    {
        return new AGridGlobalDecl(
            cloneNode(this._gridDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGridGlobalDecl(this);
    }

    public PGridDecl getGridDecl()
    {
        return this._gridDecl_;
    }

    public void setGridDecl(PGridDecl node)
    {
        if(this._gridDecl_ != null)
        {
            this._gridDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gridDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gridDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gridDecl_ == child)
        {
            this._gridDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gridDecl_ == oldChild)
        {
            setGridDecl((PGridDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
