/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AListVar extends PListVar
{
    private PValue _value_;
    private final LinkedList<PListVarTail> _listVarTail_ = new LinkedList<PListVarTail>();

    public AListVar()
    {
        // Constructor
    }

    public AListVar(
        @SuppressWarnings("hiding") PValue _value_,
        @SuppressWarnings("hiding") List<?> _listVarTail_)
    {
        // Constructor
        setValue(_value_);

        setListVarTail(_listVarTail_);

    }

    @Override
    public Object clone()
    {
        return new AListVar(
            cloneNode(this._value_),
            cloneList(this._listVarTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListVar(this);
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    public LinkedList<PListVarTail> getListVarTail()
    {
        return this._listVarTail_;
    }

    public void setListVarTail(List<?> list)
    {
        for(PListVarTail e : this._listVarTail_)
        {
            e.parent(null);
        }
        this._listVarTail_.clear();

        for(Object obj_e : list)
        {
            PListVarTail e = (PListVarTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._listVarTail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._value_)
            + toString(this._listVarTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        if(this._listVarTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator<PListVarTail> i = this._listVarTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListVarTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
