/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class TFigure extends Token
{
    public TFigure()
    {
        super.setText("figure");
    }

    public TFigure(int line, int pos)
    {
        super.setText("figure");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFigure(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFigure(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFigure text.");
    }
}
