/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class TFigur extends Token
{
    public TFigur()
    {
        super.setText("figur");
    }

    public TFigur(int line, int pos)
    {
        super.setText("figur");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFigur(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFigur(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFigur text.");
    }
}
