/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class TGrid extends Token
{
    public TGrid()
    {
        super.setText("grid");
    }

    public TGrid(int line, int pos)
    {
        super.setText("grid");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGrid(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGrid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGrid text.");
    }
}
