/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AEquateOpand extends POpand
{
    private POpequate _opequate_;

    public AEquateOpand()
    {
        // Constructor
    }

    public AEquateOpand(
        @SuppressWarnings("hiding") POpequate _opequate_)
    {
        // Constructor
        setOpequate(_opequate_);

    }

    @Override
    public Object clone()
    {
        return new AEquateOpand(
            cloneNode(this._opequate_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEquateOpand(this);
    }

    public POpequate getOpequate()
    {
        return this._opequate_;
    }

    public void setOpequate(POpequate node)
    {
        if(this._opequate_ != null)
        {
            this._opequate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opequate_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opequate_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opequate_ == child)
        {
            this._opequate_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opequate_ == oldChild)
        {
            setOpequate((POpequate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
