/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryOpmult extends POpmult
{
    private POpunary _opunary_;

    public AUnaryOpmult()
    {
        // Constructor
    }

    public AUnaryOpmult(
        @SuppressWarnings("hiding") POpunary _opunary_)
    {
        // Constructor
        setOpunary(_opunary_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryOpmult(
            cloneNode(this._opunary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryOpmult(this);
    }

    public POpunary getOpunary()
    {
        return this._opunary_;
    }

    public void setOpunary(POpunary node)
    {
        if(this._opunary_ != null)
        {
            this._opunary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opunary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opunary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opunary_ == child)
        {
            this._opunary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opunary_ == oldChild)
        {
            setOpunary((POpunary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
