/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AVarnameValue extends PValue
{
    private PVarname _varname_;
    private PFunctionCall _functionCall_;

    public AVarnameValue()
    {
        // Constructor
    }

    public AVarnameValue(
        @SuppressWarnings("hiding") PVarname _varname_,
        @SuppressWarnings("hiding") PFunctionCall _functionCall_)
    {
        // Constructor
        setVarname(_varname_);

        setFunctionCall(_functionCall_);

    }

    @Override
    public Object clone()
    {
        return new AVarnameValue(
            cloneNode(this._varname_),
            cloneNode(this._functionCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarnameValue(this);
    }

    public PVarname getVarname()
    {
        return this._varname_;
    }

    public void setVarname(PVarname node)
    {
        if(this._varname_ != null)
        {
            this._varname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varname_ = node;
    }

    public PFunctionCall getFunctionCall()
    {
        return this._functionCall_;
    }

    public void setFunctionCall(PFunctionCall node)
    {
        if(this._functionCall_ != null)
        {
            this._functionCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varname_)
            + toString(this._functionCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varname_ == child)
        {
            this._varname_ = null;
            return;
        }

        if(this._functionCall_ == child)
        {
            this._functionCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varname_ == oldChild)
        {
            setVarname((PVarname) newChild);
            return;
        }

        if(this._functionCall_ == oldChild)
        {
            setFunctionCall((PFunctionCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
