/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ARepeatControlStatments extends PControlStatments
{
    private TRepeat _repeat_;
    private TParL _parL_;
    private PLeftParam _leftParam_;
    private PRightParam _rightParam_;
    private TParR _parR_;
    private PBody _body_;

    public ARepeatControlStatments()
    {
        // Constructor
    }

    public ARepeatControlStatments(
        @SuppressWarnings("hiding") TRepeat _repeat_,
        @SuppressWarnings("hiding") TParL _parL_,
        @SuppressWarnings("hiding") PLeftParam _leftParam_,
        @SuppressWarnings("hiding") PRightParam _rightParam_,
        @SuppressWarnings("hiding") TParR _parR_,
        @SuppressWarnings("hiding") PBody _body_)
    {
        // Constructor
        setRepeat(_repeat_);

        setParL(_parL_);

        setLeftParam(_leftParam_);

        setRightParam(_rightParam_);

        setParR(_parR_);

        setBody(_body_);

    }

    @Override
    public Object clone()
    {
        return new ARepeatControlStatments(
            cloneNode(this._repeat_),
            cloneNode(this._parL_),
            cloneNode(this._leftParam_),
            cloneNode(this._rightParam_),
            cloneNode(this._parR_),
            cloneNode(this._body_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepeatControlStatments(this);
    }

    public TRepeat getRepeat()
    {
        return this._repeat_;
    }

    public void setRepeat(TRepeat node)
    {
        if(this._repeat_ != null)
        {
            this._repeat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._repeat_ = node;
    }

    public TParL getParL()
    {
        return this._parL_;
    }

    public void setParL(TParL node)
    {
        if(this._parL_ != null)
        {
            this._parL_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parL_ = node;
    }

    public PLeftParam getLeftParam()
    {
        return this._leftParam_;
    }

    public void setLeftParam(PLeftParam node)
    {
        if(this._leftParam_ != null)
        {
            this._leftParam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftParam_ = node;
    }

    public PRightParam getRightParam()
    {
        return this._rightParam_;
    }

    public void setRightParam(PRightParam node)
    {
        if(this._rightParam_ != null)
        {
            this._rightParam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightParam_ = node;
    }

    public TParR getParR()
    {
        return this._parR_;
    }

    public void setParR(TParR node)
    {
        if(this._parR_ != null)
        {
            this._parR_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parR_ = node;
    }

    public PBody getBody()
    {
        return this._body_;
    }

    public void setBody(PBody node)
    {
        if(this._body_ != null)
        {
            this._body_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._body_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._repeat_)
            + toString(this._parL_)
            + toString(this._leftParam_)
            + toString(this._rightParam_)
            + toString(this._parR_)
            + toString(this._body_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._repeat_ == child)
        {
            this._repeat_ = null;
            return;
        }

        if(this._parL_ == child)
        {
            this._parL_ = null;
            return;
        }

        if(this._leftParam_ == child)
        {
            this._leftParam_ = null;
            return;
        }

        if(this._rightParam_ == child)
        {
            this._rightParam_ = null;
            return;
        }

        if(this._parR_ == child)
        {
            this._parR_ = null;
            return;
        }

        if(this._body_ == child)
        {
            this._body_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._repeat_ == oldChild)
        {
            setRepeat((TRepeat) newChild);
            return;
        }

        if(this._parL_ == oldChild)
        {
            setParL((TParL) newChild);
            return;
        }

        if(this._leftParam_ == oldChild)
        {
            setLeftParam((PLeftParam) newChild);
            return;
        }

        if(this._rightParam_ == oldChild)
        {
            setRightParam((PRightParam) newChild);
            return;
        }

        if(this._parR_ == oldChild)
        {
            setParR((TParR) newChild);
            return;
        }

        if(this._body_ == oldChild)
        {
            setBody((PBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
