/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AMultOpmult extends POpmult
{
    private POpmult _opmult_;
    private TMult _mult_;
    private POpunary _opunary_;

    public AMultOpmult()
    {
        // Constructor
    }

    public AMultOpmult(
        @SuppressWarnings("hiding") POpmult _opmult_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") POpunary _opunary_)
    {
        // Constructor
        setOpmult(_opmult_);

        setMult(_mult_);

        setOpunary(_opunary_);

    }

    @Override
    public Object clone()
    {
        return new AMultOpmult(
            cloneNode(this._opmult_),
            cloneNode(this._mult_),
            cloneNode(this._opunary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultOpmult(this);
    }

    public POpmult getOpmult()
    {
        return this._opmult_;
    }

    public void setOpmult(POpmult node)
    {
        if(this._opmult_ != null)
        {
            this._opmult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opmult_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public POpunary getOpunary()
    {
        return this._opunary_;
    }

    public void setOpunary(POpunary node)
    {
        if(this._opunary_ != null)
        {
            this._opunary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opunary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opmult_)
            + toString(this._mult_)
            + toString(this._opunary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opmult_ == child)
        {
            this._opmult_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._opunary_ == child)
        {
            this._opunary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opmult_ == oldChild)
        {
            setOpmult((POpmult) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._opunary_ == oldChild)
        {
            setOpunary((POpunary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
