/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ADecrementExpr extends PExpr
{
    private POpor _opor_;
    private TDecrement _decrement_;
    private PExpr _expr_;

    public ADecrementExpr()
    {
        // Constructor
    }

    public ADecrementExpr(
        @SuppressWarnings("hiding") POpor _opor_,
        @SuppressWarnings("hiding") TDecrement _decrement_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setOpor(_opor_);

        setDecrement(_decrement_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new ADecrementExpr(
            cloneNode(this._opor_),
            cloneNode(this._decrement_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecrementExpr(this);
    }

    public POpor getOpor()
    {
        return this._opor_;
    }

    public void setOpor(POpor node)
    {
        if(this._opor_ != null)
        {
            this._opor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opor_ = node;
    }

    public TDecrement getDecrement()
    {
        return this._decrement_;
    }

    public void setDecrement(TDecrement node)
    {
        if(this._decrement_ != null)
        {
            this._decrement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decrement_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opor_)
            + toString(this._decrement_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opor_ == child)
        {
            this._opor_ = null;
            return;
        }

        if(this._decrement_ == child)
        {
            this._decrement_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opor_ == oldChild)
        {
            setOpor((POpor) newChild);
            return;
        }

        if(this._decrement_ == oldChild)
        {
            setDecrement((TDecrement) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
